### ISSUE TITLE
`FIRST_KW_PARAM` should use `PARAM_ORDER`

### ISSUE THREAD

**Issue by szhorvat** [igraph/stimulus#7]
`FIRST_KW_PARAM` should probably take the new order into account (specified in `PARAM_ORDER`) instead of the original order. Otherwise it's difficult to do both reordering and enforcing keyword parameters.

What do you think?

I am now looking at this:

```yaml
igraph_eccentricity_dijkstra:
    PARAMS: |-
        GRAPH graph, EDGEWEIGHTS weights=NULL,
        OUT VERTEX_QTY res, VERTEX_SELECTOR vids=ALL,
        NEIMODE mode=ALL
    DEPS: weights ON graph, vids ON graph, res ON graph vids
```

I'm trying to figure out how to make `weights` a keyword param in R, but not `vids`. Is there any solution at all with the current system?
